<a href="https://colab.research.google.com/github/AXM78251/Python_ML/blob/main/Introduction_to_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is TensorFlow?**
*** 
Tensorflow is an open source machine learning platform. It is owned and maintained by Google and is one of the largest open source machine learning libraries in the world. <br>
For our purposes we will use Tensorflow to build modeks that can do some of the following things:
* Image Classification
* Data Clustering
* Regression
* Reinforcement Learning
* Natural Language Processing

# **How it works**
*** 
Tensorflow has two main components we should understand:
<br>

*   Graphs
*   Sessions

TensorFlow works by building a graph of defined computations. Nothing is computed or stored in this graph. It is simply a way of defining the operations that have been written in code.


*   Called graphs because
different computations can be related to each other


A TensorFlow sessions allows parts of the graph to be executed. It allocates memory and resources and handles the execution of the operations and computations we've defined. <br>
In some instances we will need to run a session to be able to execute parts of the graph we've created earlier.


*   Sessions start at the lowest level of the graph where nothing is dependent on anything else
*   Then we move our way through the graph and start doing all the different partial computations that we've defined



# **Importing TensorFlow**
Make sure to select the correct version of TensorFlow from within Google Colaboratory! We want TensorFlow 2.x!

In [3]:
%tensorflow_version 2.x # This line is required at the beginning of all our notebooks

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [4]:
import tensorflow as tf # Import the tensorflow module
print(tf.version) # Make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# **Tensors**
A tensor is a generalization of vectors and matrices to potentially higher dimensions. TensorFlow represents tensors as n-dimensional arrays of base datatypes <br><br>
Each tensor represents a partially defined computation that will eventually produce a value

*   When we create our program, we will create a bunch of tensors -- will store partially defined computations in the graph
*   Later when building the graph and having the session running, we'll run different parts of the graph (i.e. execute different tensors and be able to get different results from our tensors) 
* Each tensor has a datatype and a shape

**Data Types Include**: float32, int32, string, and others <br>
**Shape**: Represents the dimension of the data






# **Creating Tensors**
Below is an example of how to create different tensors

In [5]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int32)
floating = tf.Variable(3.567, tf.float64)

The above tensors have a shape of 1 which means they are scalar values (i.e. one number)

# **Rank/Degree of Tensors**
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. The tensor we created above is a tensor with rank 0, also known as a scalar <br><br>
Below are some tensors of higher degree/ranks

In [7]:
rank1_tensor = tf.Variable(["Test", "Ok"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok"], ["Test", "Yes"]])

When we have an array or list, we immediately have rank 1 because an array can stire more than 1 value in one dimension <br><br>
By hand, we can determine the rank of a tensor by finding the deepest level of nested lists<br><br>
**To determine the rank** of a tensor, we can call the following method

In [8]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# **Shape of Tensors**
The shape of a tensor is simply the amount of elements that exist in each dimension<br><br>

To **get the shape** of a tensor we can use the shape attribute


In [9]:
rank2_tensor.shape

TensorShape([2, 2])

# **Changing Shape**
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convenient to be able to change the shape of a tensor
<br><br>
Below shows how to change the shape of a tensor


In [10]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # Reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # This will reshape the tensor to [3,2]
                                                                             
# The number of elements in the reshaped tensor MUST match the number in the original

In [11]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# **Types of tensors**
Most commonly used tensors:


*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of Variable, all these are immutable, meaning their value may not change during execution
 


# **Evaluating Tensors**

There mau be times when we need to evaluate a tensor (i.e. get its value). Since tensors represent a partially complete computation we will somwtimes need to run a session to evaluate the sensor
<br><br>
An example is below

In [ ]:
with tf.Session() as sess:  # Creates a session using the default graph
  rank2_tensor.eval() #Evaluate the respective tensor

The code above evaluated the tensor stored in the default graph which holds all operations not specified to any other graph. We can certainly create our own graphs but we will use the default for now

# **Slicing**
Slice operators (commonly used on lists, tuples, etc.) can be used on tensors to select specific axes or elements as well! <br><br>
When we slice or select elements from a tensor, we can use comma separated values inside the set of square brackets where each subsequent value references a different dimension of the tensor<br><br>
Example: tensor[dim1, dim2, dim3]
<br><br> 
A brief example is below 


In [12]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype = tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [14]:
# Now select some rows and columns from our tensor 

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


All credit for code/material above goes to Tim Ruscica, otherwise known on youtube as "Tech With Tim" <br>
Youtube: ["Tech With Tim"](https://www.youtube.com/c/TechWithTim)